### ISSUE TITLE
Options error: --secret fails with '/etc/openvpn/secret.obfs4.key': No such file or directory

### ISSUE THREAD

**Issue by GeorgeGhost** [HRomie/obfs4proxy-openvpn#1]
I know this sounds stupid but i have no idea where to get secret.obfs4.key

**Comment by HRomie** [comment]
Hi,
It seems that you did realize how to do it in the end. But if you think that the inline comments (or documentations) could be improved to avoid these kinda confusions for others, please do tell.

**Comment by GeorgeGhost** [comment]
Sure I will add some further explanation that is commented in the scripts, into the Readme
