### ISSUE TITLE
not working properly on my Ubuntu

### ISSUE THREAD

**Issue by peigongdsd** [HRomie/obfs4proxy-openvpn#3]
when I type obfs4proxy-openvpn, it doesn't print anything to the screen. 
System:Ubuntu bionic 4.15.0-88
my email:peigong2013@outlook.com

**Comment by HRomie** [comment]
That's very strange. Usually you should at least get a message telling you whats wrong.
Please open the script and replace the first line:

`#!/usr/bin/env bash`

with:

`#!/usr/bin/env -S bash -x`

and the run the script again. That will give us a pretty good idea on where its failing.
