### ISSUE TITLE
Multiple issues with setup guide

### ISSUE THREAD

**Issue by staridiot** [HRomie/obfs4proxy-openvpn#4]
I followed the tutorial in the main body and can't seem to get anything to work.

1. I'm using the basic OpenVPN client to connect to my dedicated server and my client refuses to use the shared cert provided by the server, regardless if it's embedded in the .ovpn file or separate. 
2. The sample client file for OpenVPN must be missing something for the `obfs4proxy-openvpn --export-cert -` because I can't figure out where that code goes.
3. The tutorial suggests (from what I gathered) disabling the cipher is _okay_. I would rather have a cipher enabled than disabled, the provided sample configurations for OpenVPN seem to break with a typical setup's setting.

I should make this pretty clear, I'm not very familiar with OpenVPN or the obfuscating integration and the little documentation I can find on it isn't helping the matter. I'm attempting to setup a VPN with obfuscation so Spectrum, the dicks they are will stop throttling me when I use a VPN.

### My setups
Server:
> Ubuntu 18.04
> OpenVPN 2.4.4

Client:
> Windows 10 1909
> OpenVPN Connect 3.1.3

### OpenVPN client config
```
mode p2p
dev tun_obfs4
remote serverip 1516
ifconfig 10.1.0.2 10.1.0.1
socket-flags TCP_NODELAY
user nobody
group obfs4-ovpn
persist-tun
persist-key
secret secret.obfs4.key 1
cipher none
```
When I drag it into openvpn it asks for a certificate but doesn't allow me to give it one.
### OpenVPN server config
```
mode p2p
dev tun_obfs4
ifconfig 10.1.0.1 10.1.0.2
socket-flags TCP_NODELAY
user nobody
persist-tun
persist-key
secret /etc/openvpn/secret.obfs4.key 0
cipher none
```
Server starts fine but I can't connect to it with a broken client.

Any help would be greatly appreciated, thanks.

**Comment by HRomie** [comment]
Hello staridiot,

All the mentioned issues, stem from the simple fact that you're using Windows as your client. Unfortunately the script does not support Windows clients for the time being. While it should be possible to use Windows as a client, I need to do some testings first to see the specific issues that might arise from it. I might consider adding Windows client support in a future release however. Sorry that I cannot be anymore help at this point. If you are interested, you might consider adding this project to your watch list so you'd be notified if windows client support ever added.
